# Generated by Django 3.0.2 on 2020-06-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddresses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'IpAddresses',
            },
        ),
    ]
