# Generated by Django 3.0.2 on 2020-02-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='meetings_per_week',
        ),
    ]
