# Generated by Django 3.0.2 on 2020-03-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_isLab',
            field=models.BooleanField(default=False),
        ),
    ]
