# Generated by Django 3.0.2 on 2020-02-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0002_remove_semester_meetings_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='meetings_per_week',
            field=models.IntegerField(default=None),
        ),
    ]
