# Generated by Django 3.0.3 on 2020-03-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0003_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='uId',
        ),
    ]
