# Generated by Django 3.0.3 on 2020-03-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0005_professors_ispermanant'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_isPhysics_Lab',
            field=models.BooleanField(default=False),
        ),
    ]
