# Generated by Django 3.0.3 on 2020-03-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0006_courses_course_isphysics_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_physics_lab',
            field=models.BooleanField(default=False),
        ),
    ]
