# Generated by Django 3.0.2 on 2020-03-08 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0007_rooms_is_physics_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.CharField(default=datetime.datetime(2020, 3, 8, 6, 1, 56, 717648), max_length=100)),
            ],
            options={
                'db_table': 'Module',
            },
        ),
    ]
