# Generated by Django 3.0.2 on 2020-03-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0009_auto_20200308_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='date_time',
        ),
    ]
