# Generated by Django 3.0.2 on 2020-03-08 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0011_courses_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 6, 10, 49, 5931)),
        ),
    ]
