# Generated by Django 3.0.2 on 2020-03-12 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0013_auto_20200312_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 19, 44, 36, 125214)),
        ),
        migrations.AlterField(
            model_name='temp_module',
            name='date_time',
            field=models.DateTimeField(default=None),
        ),
    ]
