# Generated by Django 3.0.2 on 2020-03-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0014_auto_20200312_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='date_time',
            field=models.DateTimeField(default=None),
        ),
    ]
