# Generated by Django 3.0.2 on 2020-04-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0016_temp_module_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Semester'),
        ),
    ]
