# Generated by Django 3.0.2 on 2020-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0017_module_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='fitness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temp_module',
            name='fitness',
            field=models.IntegerField(default=0),
        ),
    ]
