# Generated by Django 3.0.2 on 2020-04-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Scheduler', '0019_auto_20200405_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='courses_professor',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='day_time',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='day_time_professor',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='days',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='languages',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='module',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='professors',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='semester',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='temp_module',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
        migrations.AddField(
            model_name='time',
            name='_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auto_Scheduler.Users'),
        ),
    ]
